### ISSUE TITLE
Suggestion: add overriding `.btn:hover` rules with correct contrast 

### ISSUE THREAD

**Issue by evias** [rebsweb/bootstrap-colors-addon#1]
With current classes and following example:

```html
<div class="btn btn-blue">text</div>
```

when the button is `:hover`, the text will become dark (because of default bootstrap behaviour)

A possible fix for this would be to include an overwrite of the `:hover` selector, i.e.:

```css
.btn-blue { background-color: #0000ff; color: #ffffff; }
.btn.btn-blue:hover { background-color: #0000ff; color: #ffffff; } /* Note that a color change feedback is not bad, maybe the color here should be #dcdcdc */
```
